### ISSUE TITLE
Allow radius/unit to be prefilled via query string params

### ISSUE THREAD

**Issue by jsmarr** [obeattie/gmaps-radius#1]
This is a super handy tool! One simple thing that would make it even handier IMO is to look for query-string params for radius and units and prefill the form values with them. For instance http://obeattie.github.io/gmaps-radius/?radius=50&unit=mi -- that way when we're referring to a threshold like "anything in a 50-mile radius" in our code/projects, we could just link that to this URL and anyone could immediately see what that radius looks like in practice, without needing to configure anything on the page. Hopefully should be a quick tweak (could do it in JS onload if you wanna keep your HTML static). :) Thanks! js

**Comment by obeattie** [comment]
This is a good idea (sorry I didn't see this issue until recently). I'll add this/

**Comment by jsmarr** [comment]
Sweet, lemme know when it's ready and I'll start using it! ;) Thanks, js

**Comment by jsmarr** [comment]
Ooh looking at your recent commits, maybe it's already in? But from the docs it's not clear what units to use (might be worth clarifying).
