### ISSUE TITLE
$$$$  maps.google.com BILLING $$ cost vs OpenMaps

### ISSUE THREAD

**Issue by va3yyz** [obeattie/gmaps-radius#20]
As maps.google.com will cost a fee and BILLING can this be setup working with an GPL opensource MAPs like OpenMaps

GOOGLE :: maps.google.com KEY  now is fee $$$$$

**Comment by marcellusmontilla** [comment]
What kind of site do you use this on? Just in case you haven't explored [Google Maps Pricing](https://cloud.google.com/maps-platform/pricing/) yet. There is a $200 credit that you can use per month. Non-commercial sites usually don't consume this credit amount. Even a low-traffic commercial site will not consume the $200 credit.
