### ISSUE TITLE
Migrate to OpenStreetMap

### ISSUE THREAD

**Issue by cb-software** [obeattie/gmaps-radius#22]
Use the free OpenStreetMap API instead of the Google Maps API. This would eliminate the ugly warnings over the map. Although it wouldn't be Google Maps, the free and open OpenStreetMap should be used instead.

**Comment by billyprice1** [comment]
I plus one this ideal

**Comment by jopfre** [comment]
@obeattie I know you asked for a PR but I would suggest it's a new a project as most of the code is different and it uses a different build process. Perhaps consider forking it instead.

https://github.com/jopfre/osmaps-radius

**Comment by cb-software** [comment]
A fork has been made.
