### ISSUE TITLE
provide url with coordinates to pass on image

### ISSUE THREAD

**Issue by mazzie14** [obeattie/gmaps-radius#3]
Is there any way to pass on the map with drawn circles on it ? saving it ? by coordinates + poly ? or by copy pasting the image ( html 5 data img ) ?

**Comment by jsholmes** [comment]
This would be really helpful.

**Comment by vancinad** [comment]
Could someone provide an example of passing these arguments? I tried what I thought should work ("http://obeattie.github.io/gmaps-radius/index.html?r=100&u=nm&lat=41.6081111&lng=-88.0961944") but it had no effect.

**Comment by obeattie** [comment]
This should now be fixed. The link example you posted above now works 😄
