### ISSUE TITLE
Google maps gives warning SensorNotRequired

### ISSUE THREAD

**Issue by Haroenv** [obeattie/gmaps-radius#4]
Developer Error Code | Type | Description
---|---|---
SensorNotRequired | Warning | The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element.

[Source](https://developers.google.com/maps/documentation/javascript/error-messages)

**Comment by obeattie** [comment]
Fixed in 4e8c61c. Thanks! ⭐

**Comment by Haroenv** [comment]
👌
